{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pppp.fullname" . }}-https
  labels:
    {{- include "pppp.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name | quote }}
    {{- if .Values.gateway.namespace }}
    namespace: {{ .Values.gateway.namespace | quote }}
    {{- end }}
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "pppp.fullname" . }}
      port: {{ .Values.gateway.servicePort | default 80 }}
{{- if .Values.gateway.redirect.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pppp.fullname" . }}-redirect
  labels:
    {{- include "pppp.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name | quote }}
    sectionName: {{ .Values.gateway.redirect.sectionName | default "http" | quote }}
    {{- if .Values.gateway.namespace }}
    namespace: {{ .Values.gateway.namespace | quote }}
    {{- end }}
  hostnames:
  - {{ .Values.gateway.hostname | quote }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: {{ .Values.gateway.redirect.statusCode | default 301 }}
{{- end }}
{{- end }}
